//! Model architecture enumeration

use serde::{Deserialize, Serialize};

/// LLM architecture type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LlmArch {
    Unknown,
    Llama,
    Mistral,
    Mixtral,
    Gpt2,
    GptNeoX,
    Bert,
    T5,
    Bloom,
    Falcon,
    Mpt,
    Dolly,
    StableLm,
    Phi,
    Phi2,
    Phi3,
    Qwen,
    Qwen2,
    Qwen2Moe,
    Qwen3,
    Qwen2Vl,
    Llava,
    DeepSeek,
    DeepSeekMoE,
    Gemma,
    Gemma2,
    StarCoder2,
    // ... 100+ more architectures
}

/// LLM parameter count
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LlmType {
    Unknown,
    M14,
    M17,
    M22,
    M33,
    M47,
    M60,
    M70,
    M80,
    M109,
    M137,
    M140,
    M149,
    M160,
    M190,
    M220,
    M250,
    M256,
    M270,
    M335,
    M350,
    M360,
    M395,
    M410,
    M450,
    M475,
    M558,
    M700,
    M770,
    M780,
    M950,
    M0_3B,
    M0_5B,
    M0_6B,
    M0_8B,
    M1B,
    M1_2B,
    M1_3B,
    M1_4B,
    M1_5B,
    M1_6B,
    M1_7B,
    M1_8B,
    M2B,
    M2_6B,
    M2_8B,
    M2_9B,
    M3B,
    M4B,
    M6B,
    M6_9B,
    M7B,
    M8B,
    M9B,
    M11B,
    M12B,
    M13B,
    M14B,
    M15B,
    M16B,
    M20B,
    M26B,
    M27B,
    M30B,
    M32B,
    M34B,
    M35B,
    M36B,
    M40B,
    M65B,
    M70B,
    M120B,
    M142B,
    M236B,
    M290B,
    M314B,
    M405B,
    M671B,
}

impl LlmArch {
    pub fn name(&self) -> &'static str {
        match self {
            LlmArch::Llama => "llama",
            LlmArch::Mistral => "mistral",
            LlmArch::Mixtral => "mixtral",
            LlmArch::Gpt2 => "gpt2",
            LlmArch::GptNeoX => "gptneox",
            LlmArch::Bert => "bert",
            LlmArch::T5 => "t5",
            LlmArch::Bloom => "bloom",
            LlmArch::Falcon => "falcon",
            LlmArch::Mpt => "mpt",
            LlmArch::Phi => "phi",
            LlmArch::Phi2 => "phi2",
            LlmArch::Phi3 => "phi3",
            LlmArch::Qwen => "qwen",
            LlmArch::Qwen2 => "qwen2",
            LlmArch::Qwen2Moe => "qwen2.moe",
            LlmArch::Qwen3 => "qwen3",
            LlmArch::Qwen2Vl => "qwen2vl",
            LlmArch::Llava => "llava",
            LlmArch::DeepSeek => "deepseek",
            LlmArch::DeepSeekMoE => "deepseek.moe",
            LlmArch::Gemma => "gemma",
            LlmArch::Gemma2 => "gemma2",
            LlmArch::Unknown => "unknown",
            _ => "other",
        }
    }
}
